### ISSUE TITLE
SchemalessAttributes needed?

### ISSUE THREAD

**Issue by morrislaptop** [spatie/laravel-event-sourcing#100]
Hi! Love the package! 

I'm building custom repositories to store and load events from https://eventstore.com/ so I'm not using Eloquent at all. 

I liked the use of StoredEvent, except for the SchemalessAttributes requirement. This type then enforces all of Eloquent to be brought in. 

https://github.com/spatie/laravel-event-sourcing/blob/ea48283a7a0db3a5c090de799df8cf01f5918f69/src/StoredEvent.php#L24

At the moment I'm using a workaround, but it's not pretty!

```php
        use Illuminate\Database\Eloquent\Model;
        $emptyModel = new class extends Model { };
        $model = new $emptyModel();
        $model->meta_data = $metadata;

        return new StoredEvent([
            ...
            'meta_data' => new SchemalessAttributes($model, 'meta_data'),
            ...
        ]);
```

**Comment by riasvdv** [comment]
We could just use a plain array or json object, this would require a breaking change though

**Comment by morrislaptop** [comment]
Gotcha, thanks!

**Comment by freekmurze** [comment]
I'd accept a PR to the `v4` branch for this, breaking changes allowed! 👍

**Comment by morrislaptop** [comment]
Done!

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
I'm curious why you are using Even Store instead of a regular db. Could you share some info on that? If there's anything that can be done to make the integration easier, let us know 👍

**Comment by morrislaptop** [comment]
@freekmurze mainly around receiving and sending events to other services. 

Database model works well for a single service but it's hard for other services to be notified about new events. This could be done with some sort of scheduled task reading new events and remembering where it was up to, but would also have to deal with errors and retrys etc. EventStore takes care of this with a persistent subscription. 

Then the integration will also offer a worker which will receive events created from other services (through a persistent subscription) can then trigger projectors and reactors. 

There's also some other guarantees like event immutability which will ensure that data is consistent across the distributed services. The UI is also pretty good to view the events. And different streams can be "joined" in order which is useful for downstream data services to get only the events that they care about. 

The integration has been pretty easy so far, a couple of points I've noticed:

* Ability to set metadata on event creation - very important for correlation ids for example (ref: https://github.com/digitalrisks/laravel-eventstore#metadata)
* Ability to use a different stored event model per aggregate (accept it as a constructor to EloquentStoredEventRepository) - atm would have to create a repo for each different model
* Maybe separating the concerns for the aggregate stored event repo and the stored event repo for replaying all events (similar to how snapshot vs stored-event is separated) - would be important if the above is done
* The getState method in AggregateRoot could be improved to only include public properties (similar to Laravel Events - atm it's getting protected properties including aggregateVersion and aggregateVersionAfterReconstitution

I'll update here if I find anything else and I'd love your feedback on the integration once it's finished!

**Comment by freekmurze** [comment]
Thank you for sharing this.

**Comment by freekmurze** [comment]
Thank you for sharing this.

**Comment by morrislaptop** [comment]
Hi @freekmurze and @riasvdv ,

I've finished the first version of the EventStore bridge - it's at https://github.com/digitalrisks/lese. I've implemented it in both larabank-projectors and larabank-aggregates and seems to work pretty well!

Would love your feedback! Thanks for such a great package.
