### ISSUE TITLE
Question about folder structure when using artisan make

### ISSUE THREAD

**Issue by burzum** [spatie/laravel-event-sourcing#103]
By looking at the banking example, all the code of a domain is grouped in a domain folder under `app\Domain\Account`. When I installed the package in my Laravel 6 application it installed v3, I've noticed that that banking app is using 1.0. When I created my aggregate and event it ended up in `app\Aggregates` and the events also in their own folder. I prefer to keep things that belong to a domain in one folder, like the banking app. Is there any way of do this or can I simply move the classes around after I created them with `make`? 

I'm new to Laravel and the ES library but I've wrote my own framework agnostic implementation before. https://github.com/world-Architects/event-sourcing I think I might contribute to the Lara ES repository, so far I like what I see. 👍 

The only thing I don't like is that the persistence is built into the aggregate instead of passing the aggregate to a repository. This feels somehow wrong to me personally because it adds coupling and IMHO inverses the responsibility.

**Comment by freekmurze** [comment]
You can move the generated classes to anywhere you want.
