### ISSUE TITLE
Sample implementation of Snapshot ? 

### ISSUE THREAD

**Issue by nicopenaredondo** [spatie/laravel-event-sourcing#106]
Is it possible to add a sample scenario/implementation of "Snapshot" in the documentation ? I'm kinda confuse on how I can implement it.

**Comment by freekmurze** [comment]
The documentation is here: https://docs.spatie.be/laravel-event-sourcing/v3/using-aggregates/snapshots/

The testsuite contains a few examples I think.

**Comment by nicopenaredondo** [comment]
Got it. Thanks!
