### ISSUE TITLE
How Does This Compare To The ActivityLog Package?

### ISSUE THREAD

**Issue by MannikJ** [spatie/laravel-event-sourcing#107]
We have been using the [Activity Log Package](https://github.com/spatie/laravel-activitylog) since before spatie started creating these event sourcing packages.

I feel that  laravel-activity-log and laravel-event-sourcing are used to solved very similar problems, whereas the latter a bit more elaborate and sticks to a common pattern, but I am not really that deep into event sourcing. So what are the main differences of these two?
Would it even make sense to use both packages within the same app? I guess what we currently do in some cases is actually a very simple form of event sourcing by using the activity-log package. So I am thinking about refactoring our app to rely on the event sourcing package only, because I feel its more strict and expressive, because it uses a common you can remember and refer to. 

What do you think?

**Comment by freekmurze** [comment]
The big difference between the two is that event sourcing stores and organises things in such a way that you can make decisions based on the past. 

Theoretically you could also make decisions using the activity log, but that would be the same as making decisions based on the content of a log file. You could do it, but in many cases, the approach won't scaled or be maintainable.

To get a deeper understand, I suggest your read the entire documentation of both packages.
