### ISSUE TITLE
Update docs: meaning of "You should make sure that the queue will process only one job at a time."

### ISSUE THREAD

**Issue by hailwood** [spatie/laravel-event-sourcing#11]
So in the docs on https://docs.spatie.be/laravel-event-sourcing/v1/installation-setup/ there's this section

> It’s recommended that should set up a `queue`. Specify the connection name in the queue key of the `event-sourcing` config file. This queue will be used to guarantee that the events will be processed by all projectors in the right order. You should make sure that the queue will process only one job at a time. In a local environment, where events have a very low chance of getting fired concurrently, it’s probably ok to just use the `sync` driver.

It's probably helpful to provide a couple of examples of how to do this, e.g. for horizon I believe it's a case of adding something like the following to the `horizon.php` config file.

```php
'environments' => [
    'production' => [
        //...
        'event-sourcing-supervisor-1' => [
            'connection' => 'redis',
            'queue' => [env('EVENT_PROJECTOR_QUEUE_NAME')],
            'balance' => 'simple',
            'processes' => 1,
            'tries' => 3,
        ],
    ],

    'local' => [
        //...
        'event-sourcing-supervisor-1' => [
            'connection' => 'redis',
            'queue' => [env('EVENT_PROJECTOR_QUEUE_NAME')],
            'balance' => 'simple',
            'processes' => 1,
            'tries' => 3,
        ],
    ],
]
```

I've opened an issue rather than a PR as I can not think of a great way to word this.

**Comment by rubenvanassche** [comment]
Thanks! Thos was merged with #16
