### ISSUE TITLE
Unresolvable dependency resolving

### ISSUE THREAD

**Issue by wietsewarendorff** [spatie/laravel-event-sourcing#110]
I like the idea of event-sourcing and wanted to give it a try on a new project. In a controller I am firing an event, but the projector cannot load it somehow:

`Unresolvable dependency resolving [Parameter #0 [ <required> string $uuid ]] in class App\Events\MyEvent`

What am I missing here? I basically followed [this part of the docs](https://docs.spatie.be/laravel-event-sourcing/v3/using-projectors/writing-your-first-projector), looked at the [larabank-example](https://github.com/spatie/larabank-projectors) and it should not be that hard to get it up and running. Yet somehow it doesn't work.
I can see the event in the stored_events table in the database, even with the supplier uuid. But as soon as I try to use the projector (either by auto-discovery or manual) I get the error.

The event:
```
<?php

declare(strict_types=1);

namespace App\Events;

use Spatie\EventSourcing\ShouldBeStored;

class MyEvent implements ShouldBeStored
{
    public string $uuid;

    public function __construct(string $uuid)
    {
        $this->uuid = $uuid;
    }
}
```

The projector:
```
<?php

declare(strict_types=1);

namespace App\Projectors;

use Spatie\EventSourcing\Projectors\Projector;
use Spatie\EventSourcing\Projectors\ProjectsEvents;

class MyProjector implements Projector
{
    use ProjectsEvents;

    public function onMyEvent(MyEvent $event): void
    {
        // not getting here
    }
}
```

Running on php 7.4, laravel/framework 7.15, spatie/laravel-event-sourcing 3.1.5. Cleared caches, dumped the composer autoloader etc. Any idea?

**Comment by wietsewarendorff** [comment]
Restarted from scratch, and somehow it works now. I do not know what the differences are between the two attempts, or what caused the issue anyway. But it's working now...

**Comment by sandervanhooft** [comment]
Same here, issue occurs somehow when typehinting the MyEvent on the method.

```php
public function onMyEvent(MyEvent $event): void; // fails
public function onMyEvent($event): void; // succeeds
```

@wietsewarendorff does it work _with_ typehinting for you now?

**Comment by sandervanhooft** [comment]
Found the issue - and it's a bit of a weird one.

```php
public function onMyEvent(MyEvent $myEvent): void; // fails
public function onMyEvent(MyEvent $event): void; // succeeds
```

Works here if the parameter name is `$event`. Did not expect that 😄 .

@brendt is this by design? If so, perhaps clear up the docs on this?

**Comment by freekmurze** [comment]
This is by design, feel free to send PRs to the docs to make it more clear.

**Comment by sandervanhooft** [comment]
[Done](#163), thanks @freekmurze !

**Comment by wietsewarendorff** [comment]
Have to look into it again, but thanks for pointing this out and updating the docs @sandervanhooft !
