### ISSUE TITLE
Could not persist aggregate `XAggregate` because it seems to be changed by another process after it was retrieved in the current process. Expect to persist events after version 4, but version 5 was already persisted.

### ISSUE THREAD

**Issue by ccgintranet** [spatie/laravel-event-sourcing#113]
Hello,

Firstly thank you for this library.

I am wondering if you may be able to here - this is related to #65 

I have a front-end business application that communicates to a back-end CQRS app which is using this library.

Now, it's entirely possible two HTTP requests will be fired one after another that targets the same aggregate (ms apart) which causes the message "Could not persist aggregate `XAggregate` because it seems to be changed by another process after it was retrieved in the current process. Expect to persist events after version 4, but version 5 was already persisted."

The naive solution is to throttle the front-end requests to give the back-end time to persist the event - but this isn't very friendly, feasible and only works if that request is coming from the same source.

Am I missing something here or is there a simple solution? Queues do not work because the `stored_events` table gets updated before a job is placed on the queue.

What do we do in situations in which an aggregate gets updated by 2 separate processes that are close together?

Thank you in advance,

Kind Regards,

**Comment by freekmurze** [comment]
You can solve this by allowing concurrent persists.

https://github.com/spatie/laravel-event-sourcing/blob/232d64962b3160eedea216b88458e80dba275372/docs/advanced-usage/allowing-concurrent-persists.md#L6

**Comment by anabeto93** [comment]
I'm noticing the same problem that was fixed in v4 but the error is back in version 5. I've set the property to `$allowConcurrency = true;` in the aggregate root but still getting an error.

**Comment by brendt** [comment]
You could read through https://github.com/spatie/laravel-event-sourcing/discussions/214 

Maybe using the `RetryMiddleware` could fix your problem?

**Comment by keizah7** [comment]
> I'm noticing the same problem that was fixed in v4 but the error is back in version 5. I've set the property to `$allowConcurrency = true;` in the aggregate root but still getting an error.

same problem
