### ISSUE TITLE
Expose aggregate_version of StoredEvent

### ISSUE THREAD

**Issue by dilab** [spatie/laravel-event-sourcing#114]
Can we expose aggregate_version of StoredEvent class. It will enable us to use the version when building a projection. This is useful when two events happened at the same time.

**Comment by freekmurze** [comment]
I'd accept a PR for this.

**Comment by dilab** [comment]
@freekmurze done https://github.com/spatie/laravel-event-sourcing/pull/115.

**Comment by freekmurze** [comment]
Thanks, we'll continue the conversation in #115
