### ISSUE TITLE
Retrieve aggregate roots from the container

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-event-sourcing#116]
Aggregate roots are constructed on the fly in the retrieve method:

```
    public static function retrieve(string $uuid): self
    {
        $aggregateRoot = (new static());
```

I've got some usecases where I'd like to inject a service or two in an aggregate root. If aggregate roots were resolved via the container, we could use autowiring.

I did some reading on the topic, and I believe there are valid cases where DI is useful in aggregate roots. This thread was interesting: https://stackoverflow.com/questions/22449597/should-aggregate-roots-have-dependencies#:~:text=1%20Answer&text=Aggregate%20roots%20are%20very%20likely,items%20is%20using%20the%20InvoiceRepository.

**Comment by riasvdv** [comment]
This has been added here already https://github.com/spatie/laravel-event-sourcing/pull/111

Might not be on the v4 branch yet

**Comment by brendt** [comment]
Oh, nice!
