### ISSUE TITLE
php 7.3

### ISSUE THREAD

**Issue by stillzombie** [spatie/laravel-event-sourcing#12]
I have a laravel 6 app running on a php7.2, is it really necessary for this package to install to run it on php 7.3?

**Comment by freekmurze** [comment]
Yes. Feel free to fork the package and make it compatible with PHP 7.2.

**Comment by NiekVelde** [comment]
If anyone still needs a php 7.2 compatible version of laracel-event-sourcing, i've made a fork:
https://github.com/NiekVelde/laravel-event-sourcing-7.2
