### ISSUE TITLE
Handle syncReactor

### ISSUE THREAD

**Issue by dilab** [spatie/laravel-event-sourcing#125]
Currently, all reactors handle events via dispatched jobs. However, in some situations, I want the reactors to handle events synchronously. For example, when handling events from a different context. 

So similar to projectors, can we have also handle events by reactors synchronously?

https://github.com/spatie/laravel-event-sourcing/blob/master/src/StoredEvent.php#L69

**Comment by freekmurze** [comment]
It's a sensible idea. We don't have a need for this so we are not going to invest our time in it. I'd accept a PR with tests that adds this to the package.
