### ISSUE TITLE
Reactor not executed when seeding

### ISSUE THREAD

**Issue by DeroSavage** [spatie/laravel-event-sourcing#142]
Hey,

i have a problem with reactors. In my seeder i want to create an account object. Since we're trying to do everything over event sourcing, the only way to do this is to throw an event inside the seeder to create the account. I have a projector listening for that event and it works, it will create the account. Then i have a reactor listening also on the event, but this is never called. 

Is this some know issue or expected behaviour?

**Comment by freekmurze** [comment]
Reactors should get called as well. I'm assuming they are not getting called by something specific in your project.

If you think the package is in error, please submit a failing test for us to look at.
