### ISSUE TITLE
Can version 3 be upgraded to Laravel 8?

### ISSUE THREAD

**Issue by bobbarn** [spatie/laravel-event-sourcing#147]
I see you added Laravel 8 support to the unreleased version 4. Or is version 4 released but the upgrade guide says unreleased? If 4 isn't released can 3 be upgraded?

**Comment by freekmurze** [comment]
Version 4 is released, I'll update the upgrade guide.

We recommend that you upgrade to v4 of the package. We won't be adding support for Laravel 8 to v3.
