### ISSUE TITLE
Suggest UPGRADING.md mentions republishing the config

### ISSUE THREAD

**Issue by bobbarn** [spatie/laravel-event-sourcing#148]
Worth copying any changes made to your config/event-sourcing.php, republishing and adding them back. Class paths have changed.

php artisan vendor:publish --provider="Spatie\EventSourcing\EventSourcingServiceProvider" --tag="config"

**Comment by freekmurze** [comment]
Feel free to send a PR to update UPGRADING.md to your liking.
