### ISSUE TITLE
Docs are not displaying images

### ISSUE THREAD

**Issue by KMB** [spatie/laravel-event-sourcing#157]
Hi

The documentation is not displaying images.

See: 

https://spatie.be/docs/laravel-event-sourcing/v4/getting-familiar-with-event-sourcing/using-aggregates-to-make-decisions-based-on-the-past

or

https://spatie.be/docs/laravel-event-sourcing/v4/getting-familiar-with-event-sourcing/using-projectors-to-transform-events

This seem sto be a general problem with the new documenation implementation Spatie is using and is not restricted to SVGs. See also here, where the JPG of New York is not shown.

https://spatie.be/docs/image/v1/image-manipulations/optimizing-images

Regards
KMB

**Comment by Nielsvanpach** [comment]
Thanks for letting us know @KMB 
This should be fine now
