### ISSUE TITLE
Using MongoDB

### ISSUE THREAD

**Issue by granitebps** [spatie/laravel-event-sourcing#164]
I've tried creating a custom model and use https://github.com/jenssegers/laravel-mongodb package for MongoDB connection. But both the MongoDB package and this event source package needs to extend their own model. Can this package use MongoDB?

**Comment by freekmurze** [comment]
I don't have experience with Mongo.

Here's how you can use a different model and storage repository

https://spatie.be/docs/laravel-event-sourcing/v4/advanced-usage/using-your-own-event-storage-model
https://spatie.be/docs/laravel-event-sourcing/v4/advanced-usage/using-your-own-event-storage-repository

**Comment by granitebps** [comment]
Yeah, I've already done that. But the MongoDB package that I used, also need to extends their own model.

```
<?php

namespace App\Models\MongoDB;

use Spatie\EventSourcing\StoredEvents\Models\EloquentStoredEvent;
use Jenssegers\Mongodb\Eloquent\Model; // Must extends this too

class CustomStoredEvent extends EloquentStoredEvent
{
    protected $connection = 'mongodb';
    protected $collection = 'events';
}
```

And I cannot extends both of them at the same time.
