### ISSUE TITLE
PHP8 names arguments break EventHandler dependency injection

### ISSUE THREAD

**Issue by erikgaal** [spatie/laravel-event-sourcing#165]
Hi there,

First of all I would have opened a PR to fix this, if I knew how to. I'm not sure what the best way of solving this issue as as it would likely mean to be a breaking change.

PHP8 introduced named arguments, which the Laravel's dependency injection already kind of allowed. This package makes use of that for Event Handlers, so that you can choose which parameters you want to use there. The docs show examples where you use only the Event class as a parameter.

```php
public function onAccountCreated(AccountCreated $event)
{
    Account::create($event->accountAttributes);
}
```

However, now with PHP8's named argument, an Error is thrown when not all three parameters (`$event`, `$aggregateUuid`, and `$storedEvent`) are defined in the EventHandler method.

One workaround, which is not very appealing is to change the docs and force all parameters to be implemented.

I'm not sure of another solution but it might be promising to look in Laravel's core and see how they implemented this.

**Comment by freekmurze** [comment]
@brendt could you take a look at this one?

**Comment by sebastiandedeyne** [comment]
Would have to see a full trace to be sure, but I assume this is Laravel's `App::call()` method that isn't compatible with named parameters yet, and will be patched by PHP 8's release.

It's what we're using internally, if the error trace goes through a different method that our `handle` method, it's a different issue.

https://github.com/spatie/laravel-event-sourcing/blob/3e679e9dd35d8b6bd257991de2b2d9ac12af708a/src/EventHandlers/HandlesEvents.php#L45

**Comment by brendt** [comment]
fixed with newer Laravel releases
