### ISSUE TITLE
4.5.6 Stored metadata is not reset when using CustomStoredEvent

### ISSUE THREAD

**Issue by reijo12** [spatie/laravel-event-sourcing#166]
When using CustomStoredEvent to have meta data on all events. The metadata is stored into stored_events table, but when accessing the event from projector the meta data is not present in the events. 
After looking into StoredEvent.php class it seems that the original events metadata is used always. 

Since the version 4.5.4 this function started to return original event with its metaData and not using the meta data that is passed from constructor.
![image](https://user-images.githubusercontent.com/21123006/97980454-79974e80-1dd9-11eb-9bac-e3a135b32efa.png)

**Comment by freekmurze** [comment]
Feel free to send a PR with tests for us to look at.
