### ISSUE TITLE
persistInTransaction

### ISSUE THREAD

**Issue by dilab** [spatie/laravel-event-sourcing#168]
Any example of using `persistInTransaction`? What is the use case of this static method?

**Comment by morrislaptop** [comment]
IMO It's to ensure that events across aggregated all succeed. 

For example if we had an event and bookings...?

```php
$booking->finalize(); // completes a booking for an event and issues a ticket

if ( eventIsFull() ) {
    $event->filled();
}

AggregateRoot::persistInTransaction($booking, $event);
```

This would ensure that the booking is only finalized if the event is also marked as full.

**Comment by dilab** [comment]
@morrislaptop thanks
