### ISSUE TITLE
replay projection in production

### ISSUE THREAD

**Issue by dilab** [spatie/laravel-event-sourcing#169]
How do we replay projection in a production environment?

For example, we have about 100k events, to replay, it takes about 15 minutes, if we do this live, new events may come in and the projection will not be up to date after the replay. 

So aside from schedule a system down time, how do we replay the projection gracefully?

**Comment by freekmurze** [comment]
The package has no opinion on how to do this and there are many routes to achieve this.

The easiest would be to have system downtime. Another route you could go for is to create another projector that listens for incoming events on production. When replaying the events of the old projection you could write it in the same table where your new projection writer in. It's a bit cumbersome.

There are other ways to go about this too, I suggest that your Google around for other strategies. Like mentioned before, the package has no opinion on how replays should be done.
