### ISSUE TITLE
All methods of object get serialized when using an object as a property of an event

### ISSUE THREAD

**Issue by rsdrsd** [spatie/laravel-event-sourcing#174]
When I use an instantiated object (some sort of a model), with a few properties and some simple helper methods. The methods also get serialized in the stored event. How can I let it only serialize the properties of the event? I tried several solutions by adding `__sleep`, `__serialize`, `__unserialize` etc to the class of the object, but that didn't work out. Is there a general method on how to solve this, and not rewriting the normalizers, because that looks pretty difficult.

**Comment by brendt** [comment]
Always keep in mind to pass only necessary data to an event. Instead of passing the model, pass its ID or UUID and store that. You could add a method on the event to retrieve the model from its ID, but serializing the model itself won't work.
