### ISSUE TITLE
Events as DTO's

### ISSUE THREAD

**Issue by morrislaptop** [spatie/laravel-event-sourcing#175]
With the release of 4.0, events now extend ShouldBeStored which means they can no longer extend a DataTransferObject. 

I quite liked this pattern, and it seems @brendt has had this idea in the past - https://github.com/spatie/data-transfer-object/issues/93#issuecomment-565337938

Just wondering if there's a new recommended approach?

**Comment by brendt** [comment]
I'll also quote [my response](https://github.com/spatie/data-transfer-object/issues/93#issuecomment-740370409) here:

I'm not sure this should be a package. Since the ES package is extensible enough, I think it's best to solve these problems on a project-based level. Also keep in mind that you probably don't need to use DTOs anymore if you're using PHP 8.

**Comment by morrislaptop** [comment]
Thanks @brendt, nice to know where things are headed. Something that PHP8 isn't solving is constructing objects from arrays of (serialized) data as easy as possible. So looking forward to v3 of the DTO package for that.

It would be great if v3 of the DTO package had a trait we could use for this behaviour instead of having to extend a base class. 

Something like:

```php
trait DataTransferObjectConstructor
{
    public function __construct(...$args)
    {
        if (is_array($args[0] ?? null)) {
            $args = $args[0];
        }

        $class = new DataTransferObjectClass($this);

        foreach ($class->getProperties() as $property) {
            $property->setValue($args[$property->name] ?? null);
        }

        $class->validate();
    }
}

#[CastWith(DataTransferObjectCaster::class)]
class MyEvent extends StoredEvent
{
    use DataTransferObjectConstructor;

    public OtherDTO $otherDTO;
    
    public OtherDTOCollection $collection;
    
    #[CastWith(ComplexObjectCaster::class)]
    public ComplexObject $complexObject;
    
    public ComplexObjectWithCast $complexObjectWithCast;
    
    #[NumberBetween(1, 100)]
    public int $a;
}
```
