### ISSUE TITLE
Persist in transaction

### ISSUE THREAD

**Issue by rsdrsd** [spatie/laravel-event-sourcing#176]
If I want to persist 2 or more aggregate roots in one transaction I can use the `persistInTransaction` method. But when I want to store the events globally in a certain order it doesn't seem possible, because the `persistInTransaction` stores the events in the order of the aggregates listed in `persistInTransaction` method.

How can I for example store in one transaction the following:

id | aggregate | event
-- | -- | --
1 | aggregateRoot1 | WalletWithdrawn
2 | aggregateRoot2 | OrderCreated
3 | aggregateRoot2 | OrderFinished
4 | aggregateRoot1 | WalletDeposited

Instead of

id | aggregate | event
-- | -- | --
1 | aggregateRoot1 | WalletWithdrawn
2 | aggregateRoot1 | WalletDeposited
3 | aggregateRoot2 | OrderCreated
4 | aggregateRoot2 | OrderFinished

**Comment by dilab** [comment]
@rsdrsd does it matter to you since they are two different aggregates?

**Comment by rsdrsd** [comment]
Not for the aggregate itself, but it could be for sideeffects or
projections.

**Comment by dilab** [comment]
I see, it is hard to imagine your use case without a real example. 

In general, projections should be side-effect free

**Comment by rsdrsd** [comment]
If 2 aggregates update the same projection it could become a problem. It
would be nice if we could add events from aggregates on the fly in the same
way as persistInTransaction.

**Comment by dilab** [comment]
maybe you can separate the projections as they are cheap to create.
