### ISSUE TITLE
Ability to run Temporal Query 

### ISSUE THREAD

**Issue by dilab** [spatie/laravel-event-sourcing#178]
One feature of ES is able to perform a temporal query as discussed in https://martinfowler.com/eaaDev/EventSourcing.html

```
Temporal Query: We can determine the application state at any point in time. 
Notionally we do this by starting with a blank state and rerunning the events up to a particular time or event. 
We can take this further by considering multiple time-lines (analogous to branching in a version control system).
```

Which would require `AggregateRoot::retrieve` to add an additional parameter (DateTimeImmutable $pointOfTime) to reconstitute aggregate root from that point of time.

**Comment by freekmurze** [comment]
Maybe it would be better to have a dedicated method `retrieveUntil` for this which would accept a `DateTime`

Feel free to PR this with updated tests and docs.
