### ISSUE TITLE
Question - Best practises regarding CRUD events

### ISSUE THREAD

**Issue by spaceemotion** [spatie/laravel-event-sourcing#18]
Due to (strong) auditing requirements I am implementing event-sourcing in my latest client project. I've read the docs and watched the introductionary video, but I'm currently debating on how to go about "best practises" when using this library.

Let's say I got an Invoice model with attributes like `hours` and `rate`. Initially I thought about creating the following events:

- `CreateInvoice`
- `UpdateInvoice`
- `DeleteInvoice`

However, looking at the examples provided, you've added events like `MoneyAdded` and `MoneySubtracted`.

So here are my questions:
1. **Should events be in the past or present?**
   I think of the event store kind of like a git commit history. In which the "common practise" is to write them in present tense as if they're an action ("this commit will add, fix ...").
2. **Should I split up my fields into separate events?**
   Instead of a general "Update" event, create extra ones like:
   - `UpdateInvoiceHours`
   - `UpdateInvoiceRate`

Some additional questions:
1. **How do you deal with future code changes?**
   - What If I have changes in my code structure (event if it's just namespaces moving around), would I have to write a migration that "fixes" my past events?
   - What If I have had an "update" event and now split it up into more detailed events. Do I have to keep the previous instance?

Many thanks in advance!

**Comment by adrianb93** [comment]
Spatie has a style guide that provides a sensible explanation of why you would name your events in a past-tense: https://guidelines.spatie.be/code-style/laravel-php#naming-classes

These naming decisions are up to you for your project. It's a style decision.

If you're setting hours, an `InvoiceUpdated` event is fine. In the bank example, you wouldn't want to set that value. You'd want to increment or decrement it. This is so the correct calculation is applied to the existing aggregate vs. calculating based on the currently projected data.

**Comment by adrianb93** [comment]
As for your additional question, I haven't had to split/rework event logic yet. I think there is a Full-Stack Radio podcast episode that went over that topic. Might have been one of these:

* http://www.fullstackradio.com/85
* http://www.fullstackradio.com/95

A good rule of thumb is set the value in your created or updated event unless:

* It is a state change
* An existing attribute is being mutated based on previous data

The above considerations have worked well for me thus far.
