### ISSUE TITLE
Making sure projector get handled in the right order

### ISSUE THREAD

**Issue by stillzombie** [spatie/laravel-event-sourcing#21]
Maybe this is something i could not find on the docs, so my case is i have 2 projectors listening to the same event

one projector to update a model second one to log the status of that model

so for me the second projector happen first, storing the wrong(old) values on the log.

So of course i would like to make a pr maybe i can update the docs or the example to make rhis more clear, but i dont understand how to achieve this.

Regards

**Comment by erikgaal** [comment]
I think the same logic applies as Laravel’s events applies here. Listeners should never depend on the execution order. If you need two listeners, or in this case projectors, to run in a specific order, they should be called from one another.

You could call the logic for the second projector from the first projector, or implement the logging projector in a way that it does not depend on the sequence of execution.
