### ISSUE TITLE
Projectors are not being registered

### ISSUE THREAD

**Issue by aroutinr** [spatie/laravel-event-sourcing#226]
Steps to reproduce.

- Fresh Laravel 8 Install
- Composer require spatie/laravel-event-sourcing
- Create Aggregate, Events and Projectors (Following official docs)
- php artisan event-sourcing:list 
RESUTLS IN:
No projectors registered

No reactors registered

If i downgrade spatie/laravel-event-sourcing from v5 to v4 it works.

I also git clone larabank-aggregates, on laravel-event-sourcing v4 works great, when upgrading to v5 stop working.

I dont know if its something in my computer, but seems a bug.

Took me almost 5 hours to figure it out.

LARABANK-ORIGINAL
![Captura de pantalla 2021-06-13 a la(s) 11 58 51 p  m](https://user-images.githubusercontent.com/48656913/121837394-7b948a80-cca3-11eb-87c0-8387b7367491.png)

LARABANK UPGRADING LARAVEL-EVENT-SOURCING TO V5
![Captura de pantalla 2021-06-13 a la(s) 11 59 13 p  m](https://user-images.githubusercontent.com/48656913/121837403-80593e80-cca3-11eb-8685-5e7871840c8e.png)

**Comment by brendt** [comment]
Do your projectors extend the `Projector` class? Also, what's the config value of `auto_discover_projectors_and_reactors` and `auto_discover_base_path` ?

**Comment by brendt** [comment]
FYI I can confirm the list command had a bug, but it was unrelated to projectors actually registering automatically. This bug has been fixed: https://github.com/spatie/laravel-event-sourcing/releases/tag/5.0.4

**Comment by aroutinr** [comment]
Yes the projectors are extending the Projector class and the config value are the defaults one.

I the artisan command works now but I thought that the error I was getting was because the projectors were not being detected but it is not, I still have the same problem.

Let me explain a little more the problem. Im following the steps described in the document, using the artisan commands to generate aggregates, projectors, etc. I create a simple controller, everithing works greate, stored_events table get filled in the database but whe go in the projectors it fail, the error is 
**ArgumentCountError
Too few arguments to function App\Projectors\AccountProjector::onAccountCreated(), 1 passed in .../vendor/spatie/laravel-event-sourcing/src/EventHandlers/HandlesEvents.php on line 24 and exactly 2 expected**

It seems it can get the $aggregateUuid because if i remove it from the onAccouncCreate method it show and dartabase error for the uuid colum not having default value and if i dd() in the $event it show data so its being passed.

Like i said i dont kwows if it something with my computer, im using mac with valet and obviusly php 8.

This happend only with v5, with v4 everething works.

Im testing in a Fresh Laravel 8 only and pull in. the event-sourcing packages. I can upload to a repo if you need.

Also triying to figured out the problem to make a PR but no luck for now...

Ill share some screenshoots....

**ArgumentCountError
Too few arguments to function App\Projectors\AccountProjector::onAccountCreated(), 1 passed in .../vendor/spatie/laravel-event-sourcing/src/EventHandlers/HandlesEvents.php on line 24 and exactly 2 expected**
![Captura de pantalla 2021-06-15 a la(s) 1 06 31 a  m](https://user-images.githubusercontent.com/48656913/121996166-1d84a780-cd76-11eb-89ab-fb14891d6f32.png)

**dd() of $event in AccountProjector**
![Captura de pantalla 2021-06-15 a la(s) 1 08 59 a  m](https://user-images.githubusercontent.com/48656913/121996299-56bd1780-cd76-11eb-8001-067890cc74ff.png)

**Comment by brendt** [comment]
You cannot pass any other parameters to projector or reactor methods besides the event. The event itself now has a method to access it: `$event->aggregateRootUuid()`. 

Make sure to take a look at the changelog: https://github.com/spatie/laravel-event-sourcing/blob/main/CHANGELOG.md#500---2021-06-09

> $storedEvent and $aggregateRootUuid are no longer passed to event handler methods. Use $event->storedEventId() and $event->aggregateRootUuid() instead. (#180)

**Comment by aroutinr** [comment]
I see, honestly, I hadnt seen the changelog i was just looking at the documentation on the Spatie.be page here https://spatie.be/docs/laravel-event-sourcing/v5/using-projectors/creating-and-configuring-projectors#getting-the-uuid-of-an-event and i know there was something missing.

Thanks for answering.
