### ISSUE TITLE
Utilise composer's PSR-4 autoload for projector/reactor auto-discovery?

### ISSUE THREAD

**Issue by axit-joost** [spatie/laravel-event-sourcing#26]
Would it be a useful idea to leverage composer's PSR-4 autoload for paths to scan for projectors and reactors? For instance, I have:

```jsonc
{
    // ...
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            "Domain\\": "src/"
        }
    },
    // ...
}
```

Also, might it not be more efficient to use composer's autoload as a source instead of using `Finder` to traverse the filesystem?

Just a thought.

**Comment by freekmurze** [comment]
Feel free to submit a PR to optimize things. Of course all current test should still pass.
