### ISSUE TITLE
Concurrency transactions

### ISSUE THREAD

**Issue by ahmed-alaa** [spatie/laravel-event-sourcing#3]
I'm quite interested in `spatie/event-sourcing` packages, I tried to check how the concurrent operations is handled and looks for me that at the current implementation we use `Transactional Locks`.

- I tried to concurrent `Withdraw` of same account and had to wait until 1st operation is done to process the 2nd operations.

-  I tried to concurrent `Add` operation for 2 different users and for reading was also had to wait for 1st operation.

**How can I reproduce it**

Simple, use this example [spatie/larabank-aggregates](https://github.com/spatie/larabank-aggregates) and try to do concurrent operations

**The goal**
- The goal of this issue to make sure that I'm right regarding the `DB locks`
- What's the next plan to make it more flexibility as well as solves the `OCC` problem?

**Comment by freekmurze** [comment]
I don't have any plans in this regard as I haven't run into the issue yet.

If this can be solved in a simple way, I'd accept a PR with tests that handles the issue.

**Comment by ahmed-alaa** [comment]
I'll try to take a look into and share my thoughts about it before doing the PR
