### ISSUE TITLE
Projectors and Reactors still trigger in tests despite using Event::fake()

### ISSUE THREAD

**Issue by TobiasJ** [spatie/laravel-event-sourcing#30]
Hi,

according to the [docs](https://docs.spatie.be/laravel-event-sourcing/v1/using-aggregates/testing-aggregates/#disabling-dispatching-events) when testing Aggregates you can prevent Projectors and Reactors from being fired by using Laravels `\Illuminate\Support\Facades\Event::fake();`. I tried it but they (Projectors and Reactors) are still triggered when building the Aggregate with the `given` method.

Tried it with a fresh project. Maybe it doesn't work as expected or I did a mistake. If I understood the `Event::fake()` correctly "global" Events (not related to a `Model`), are not faked?

Tried the following in a fresh installed project.

Event:
```php
<?php

namespace App\StorableEvents;

use Spatie\EventSourcing\ShouldBeStored;

final class TestHappened implements ShouldBeStored
{
    /** @var string */
    public $text;

    public function __construct(string $text)
    {
        $this->text = $text;
    }
}

```

Aggregate:
```php
<?php

namespace App\Aggregates;

use Spatie\EventSourcing\AggregateRoot;
use App\StorableEvents\TestHappened;

final class TestRootAggregate extends AggregateRoot
{
    public function doSomething(string $text)
    {
        $this->recordThat(new TestHappened($text));

        return $this;
    }
}

```

Projector (tested with Reactor too, same code):
```php
<?php

namespace App\Projectors;

use App\StorableEvents\TestHappened;
use Spatie\EventSourcing\Projectors\Projector;
use Spatie\EventSourcing\Projectors\ProjectsEvents;

final class TestProjector implements Projector
{
    use ProjectsEvents;

    protected $handlesEvents = [
        TestHappened::class => 'onTestHappened'
    ];

    public function onTestHappened(TestHappened $event)
    {
        // This should not be echo'd while running the tests.
        echo PHP_EOL.get_class($this).': '.$event->text.PHP_EOL;
    }
}

```

Test:
```php
<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;
use App\Aggregates\TestRootAggregate;
use App\StorableEvents\TestHappened;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testProjectorIsNotTriggeredWhenEventsAreFaked()
    {
        Event::fake(); // Do not trigger Projectors and Reactors

        TestRootAggregate::fake()
            ->given(new TestHappened('First Test')) // This one should not be projected
            ->when(static function (TestRootAggregate $root) {
                $root->doSomething('Second Test');
            })
            ->assertRecorded(new TestHappened('Second Test'));
    }
    // ...
}
```

Test result (highlighted output should not be displayed/echoed):
![Screenshot](https://user-images.githubusercontent.com/4747713/67958451-82b67400-fbf7-11e9-86f5-b7acd8e13572.png)

**Comment by danielwaghorn** [comment]
I also have the same issue which is manifesting itself by the test failing because an aggregate UUID isn't being supplied to the projector.

Ideally `Event::fake()` would solve this by not allowing the projectors to run, however regardless of whether the `fake()` method is called in the `setUp` in the test or just before the actual test case it still runs.

```
TypeError : Argument 2 passed to App\Projectors\InvoiceProjector::onRaiseFirstInvoice() must be of the type string, null given
```

I notice that this is when using the `given` method as below:

```php
BookingAggregate::fake()
            ->given(new RaiseFirstInvoice)
            ->when(function (BookingAggregate $aggregate) {
                $aggregate->raiseInvoice();
            })
            ->assertRecorded(new RaiseSecondInvoice)
            ->assertNotRecorded([
                RaiseFirstInvoice::class,
                RaiseRegularInvoice::class,
            ]);
```

The tests run fine if I remove the Projector.

**Comment by TobiasJ** [comment]
Short update, after the long weekend, hope y'all had a good one. Took a quick look at the `Spatie\EventSourcing\Projectionist` Class and right now it seems that the `Spatie\EventSourcing\Projectionist::withoutEventHandlers` method suits this case. When I call the method (`app(Spatie\EventSourcing\Projectionist::class)->withoutEventHandlers()`) before faking the Aggregate the Projectors and Reactors of course do not get triggered. Facade usage `\Spatie\EventSourcing\Facades\Projectionist::withoutEventHandlers();` is possible too.

**This only works when you don't want any Projectors and Reactors to be triggered.**

**Comment by riasvdv** [comment]
Does calling `withoutEventHandlers()` fix all the issues you're having? Or is there still some unexpected behaviour?

**Comment by TobiasJ** [comment]
Right now it does fix the issue for me. Couldn't come up with a test scenario where this won't work as we can just trigger manually generated Events to test Projections and Reactions.

But it would be nice to have an option (like `retrieve`) to supply a UUID to the `FakeAggregateRoot` in case they are needed for Projections in Integration/Feature Tests. That would also solve @danielwaghorn issue with the Aggregate UUID not being supplied to the Projector.

**Comment by danielwaghorn** [comment]
I can confirm that adding `Projectionist::withoutEventHandlers();` lets my tests run successfully. This works for me as I'm just testing the Aggregate as a unit. If I'm doing an integration test I tend to want the events handled by the Projectors and therefore present in the database to assert against.

Is this worth me making a PR to the docs to suggest this as a suitable means of disabling projectors rather than `Event::fake()`?

**Comment by riasvdv** [comment]
Feel free to do so! I'd suggest just adding the `Projectionist::withoutEventHandlers();` part with some extra explanation, the `Event::fake()` can still be used to prevent storing the events as that uses Laravel's event system
