### ISSUE TITLE
Not able to allow concurrent persists.

### ISSUE THREAD

**Issue by anabeto93** [spatie/laravel-event-sourcing#302]
According to this [allowing concurrent persists doc](https://github.com/spatie/laravel-event-sourcing/blob/232d64962b3160eedea216b88458e80dba275372/docs/advanced-usage/allowing-concurrent-persists.md#L6), the aggregateroot can be set to allow concurrent persists which worked fine in v4. 

```php
protected static bool $allowConcurrency = true;
```

Currently using it in v5, have set the property but it has not effect and still throws the error `Could not persist aggregate ...`

**Comment by brendt** [comment]
Please refer to [this discussion](https://github.com/spatie/laravel-event-sourcing/discussions/214) to read about how we handle concurrency in v5, make sure to check out the `RetryMiddleware` in combination with the command bus.
