### ISSUE TITLE
Aggregate Partial is ignored when creating a snapshot

### ISSUE THREAD

**Issue by saschanowak** [spatie/laravel-event-sourcing#307]
I'm playing around with this package and noticed, that when following the documentation for [aggregate partials](https://spatie.be/docs/laravel-event-sourcing/v5/advanced-usage/aggregate-partials) and creating a snapshot of the aggregate root, the state of the partial is not stored in the snapshot. 
Not sure if that is intended or a bug, as I didn't find a test for this usecase and the documentation didn't mentions snapshots and aggregate partials.

**Comment by etahamer** [comment]
@nlx-sascha

> I'm playing around with this package and noticed, that when following the documentation for [aggregate partials](https://spatie.be/docs/laravel-event-sourcing/v5/advanced-usage/aggregate-partials) and creating a snapshot of the aggregate root, the state of the partial is not stored in the snapshot. Not sure if that is intended or a bug, as I didn't find a test for this usecase and the documentation didn't mentions snapshots and aggregate partials.

1. Is your partial aggregate root is Public property of your aggregate?
2. Are the properties that you expect to snapshot public in aggregate partial?

**Comment by nlx-sascha** [comment]
Hey @etahamer,

thanks for the quick response.

Without trying it deeper I think making the AggregatePartial public does not feel right. Correct me if I'm wrong, but the interaction with the AggregatePartial should not be possible from outside. Thats when you need to proxy all functions from the AggregateRoot to the AggregatePartial like in the documentation example.
Also when reading the code the `useState` function only handles scalar values and does not convert the values of the aggregate partial to the correct object:
![image](https://user-images.githubusercontent.com/1643495/148660770-aa67b266-1295-448b-8679-f26a841071a1.png)

**Comment by brendt** [comment]
Partials should indeed not be made public. I'd say this issue is mostly an oversight, though I'm not sure whether it can be easily fixed. I welcome a PR that addresses the issue.
