### ISSUE TITLE
Docs cannot be switched to v7 in persistent way, stuck on references to v5

### ISSUE THREAD

**Issue by mikemunger** [spatie/laravel-event-sourcing#313]
Hello there, just reporting an error in the docs usability - it seems v7 docs cannot be viewed by freely clicking around the nav as intended.

Example: https://spatie.be/docs/laravel-event-sourcing/v7/introduction

Has warning message you are viewing v5, the dropdown version switcher will not honor v7, also there are 2 options in the dropdown for v7 instead of 1, and there seems to be no option for v5 in the dropdown. All nav links point to /v5/ uri segment resulting in a redirect loop error when clicked.

You can get to the desired v7 doc page only by clicking the v5 nav bad link, then manually updating the browser location to v7 uri segment.

**Comment by brendt** [comment]
It's fixed, thanks @riasvdv
