### ISSUE TITLE
AggregateRoot Method is called if Argument has no type-hint

### ISSUE THREAD

**Issue by fabianpnke** [spatie/laravel-event-sourcing#341]
PHP Version: 8.1.5
Laravel Version: 9.11.0
spatie/laravel-event-sourcing Version: 7.2.0

Hi there,

Today I came across the Situation where Method `two` was getting called when using the AggregateRoot with Method `one` inside the Application. I wondered why this was happening cause I had never used the AggregateRoot with Method `two` anywhere yet. After some experimenting and debugging, I found out that this only happens if the Argument in Method `two` is not type-hinted.

Here are some examples for a better understanding:

Scenario 1 (`two` is called):
```php
<?php

class SomethingAggregateRoot extends AggregateRoot
{
    public function one(string $foo): self
    {
        ...
        $this->recordThat(new SampleEvent());
        ...
        return $this;
    }

    public function two($without_typehint): self
    {
        ...
        $this->recordThat(...);
        ...
        return $this;
    }
}

SomethingAggregateRoot::retrieve($uuid)
    ->one('laravel')
    ->persist();
// Result: two was called
```

Scenario 2 (`two` is not called):
```php
<?php

class SomethingAggregateRoot extends AggregateRoot
{
    public function one(string $foo): self
    {
        ...
        $this->recordThat(new SampleEvent());
        ...
        return $this;
    }

    public function two(boolean $with_typehint): self
    {
        ...
        $this->recordThat(...);
        ...
        return $this;
    }
}

SomethingAggregateRoot::retrieve($uuid)
    ->one('laravel')
    ->persist();
// Result: two was not called
```

Is this an expected behaviour or a bug/defect?

Thanks for checking and clarifying,
Fabian

**Comment by freekmurze** [comment]
To my knowledge, our packages wouldn't call a custom method like `two`.
Could you create a minimal Laravel app in which the problem is reproduced?

**Comment by fabianpnke** [comment]
Please see https://github.com/fabianpnke/laravel-event-sourcing-issue-341-demo

I've managed to reproduce a behaviour in that the problem results in a 500 Server error by removing a type hint from the method.

**Comment by mariolorente** [comment]
Hi,

same here, when there is a public method in an aggregate with non typed params the app totally breaks.

The break occurs exactly inside the apply function of AggregateRoot.php, in the Handlers section.

**Comment by mariolorente** [comment]
mixed doesnt work as a type either.

**Comment by zackrowe** [comment]
I've also ran into this bug. I believe the issue is in the AggregateRoot line `259`. The method doesn't get filtered when the event gets passed to the `accepts()` method since the method argument is defined as `mixed`. 

Maybe a method could be added to `Handlers` to filter methods that don't take a specific argument type? In this case `ShouldBeStored`?

**Comment by zackrowe** [comment]
I've opened a PR in the better-types repository that can hopefully help address this issue. https://github.com/spatie/better-types/pull/3

**Comment by zackrowe** [comment]
@freekmurze I've tested the latest changes in version `7.2.3` in my project and I believe this issue has been resolved.

**Comment by fabianpnke** [comment]
Hi @zackrowe and @freekmurze
I've bumped the package to the latest version in the example repo I've provided. And now it works!
Thanks @zackrowe for providing a fix for this issue.
