### ISSUE TITLE
Snap Shots.

### ISSUE THREAD

**Issue by kimuliSiraje** [spatie/laravel-event-sourcing#36]
I have tried different event sourcing libraries for PHP and I find this easier and straight forward.
I request to add in a "snap shot" feature.

Thanks!

**Comment by freekmurze** [comment]
I would love the have a feature that work similar to how EventSauce does it. Currently I don't have the time to implement this myself. 

I would accept a PR that adds this. Make sure to include docs and tests.

**Comment by kimuliSiraje** [comment]
Ok, I will find sometime and implement that!

**Comment by riasvdv** [comment]
See #48
