### ISSUE TITLE
Issue when using with Telescope ViewWatcher

### ISSUE THREAD

**Issue by traubisoda** [spatie/laravel-event-sourcing#39]
Hi!

If I use the laravel-event-sourcing package with Laravel Telescope, I get the following error when trying to open any page on the site:
```
ReflectionException
Function Spatie\EventSourcing\EventSubscriber@handle() does not exist

in: vendor/laravel/telescope/src/Watchers/ViewWatcher.php:123
```

This happens after installing both packages freshly with their default configurations.

The error goes away, if I disable Telescope's view watcher.

I would be happy to send a PR to solve this, but I couldn't identify the root of the issue.

Used versions:
Laravel: 6.2
Telescope: 2.1
laravel-event-sourcing: 2.0, but it also happens with v1

**Comment by riasvdv** [comment]
Seems to be because of this new release of Telescope https://github.com/laravel/telescope/pull/766 

I've created an issue on the Telescope repo https://github.com/laravel/telescope/issues/793

**Comment by traubisoda** [comment]
Thanks @riasvdv, in that case I'll close this one.
