### ISSUE TITLE
[Question] Is it a good idea to convert User registration into event sourcing?

### ISSUE THREAD

**Issue by rogervila** [spatie/laravel-event-sourcing#40]
Hello,

I am wondering if it is a good idea to convert User registration into event sourcing.

For example, in order to handle user registration, the [RegisterController ](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php#L65) could be modified to retrieve a `UserAggregate` and persist the user data.

```php
    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\User
     */
    protected function create(array $data)
    {
        /*return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);*/

        $uuid = Str::uuid();
        UserAggregate::retrieve($uuid)->create($data)->persist();

        return User::uuid($uuid);
    }
```

The same behavior could be extended to other Auth controllers, like password resets and email verification.

Is this a good idea? Has anybody experienced any issue/stopper by applying these modifications?

Thank you very much.

**Comment by riasvdv** [comment]
This is the best way to go about it, yes. If you do not event source your users, you might run into a situation where older events rely on users that are not there anymore when you create a new projector.

**Comment by rogervila** [comment]
Thank you @riasvdv
