### ISSUE TITLE
Prevent loops when sending events into Aggregate methods

### ISSUE THREAD

**Issue by mvehar-preskok** [spatie/laravel-event-sourcing#419]
For some events we have a lot of data that needs to passed as arguments into aggegateRoot methods.

To s that we tried with passing event objects directly into aggregateRoot methods, but the code goes into endless loop. 

The AggregateRoot contains part inside ```apply``` function which checks if any of the aggregateRoot methods can process it and causes the endless loop.

Suggestion -> either enable the option to disable this behaviour (prevent checking which function has this event class as argument) or make private properties protected to be able to override the ```apply``` method correctly.

**Comment by mvehar-preskok** [comment]
One quick solution could be making the ```$appliedEvents``` property ```protected``` instead of private

**Comment by sebastiandedeyne** [comment]
I'm open to a PR that makes parts `protected` instead of `private` where it makes sense.

That said, the way we solve this is by creating data objects and assigning them as event properties.

```php
class BlogPostData
{
    public function __construct(
        public string $name,
        public string $content,
        // …
    ) {
    }
}

class BlogPostCreated extends ShouldBeStored
{
    public function __construct(
        public BlogPostData $blogPost
    ) {
    }
}

class BlogPostAggregateRoot extends AggregateRoot
{
    public function create(BlogPostData $blogPost): self
    {
        return $this->recordThat(new BlogPostCreated($blogPost));
    }
}
