### ISSUE TITLE
Integration with hyn/multi-tenant and PHPUnit

### ISSUE THREAD

**Issue by fhusquinet** [spatie/laravel-event-sourcing#42]
Hi!

I have a weird issue when using this package with hyn/multi-tenant. When I am running tests with PHPUnit everything fails after the first test.

```php
Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> string $storedEventRepository ]] in class Spatie\EventSourcing\EventSubscriber
```

Looks like the singleton binding for the EventSubscriber isn't used/ran after the first test is run. The class doesn't receive the required $storedEventRepository parameter when created, which should contain the value in the config file (config('event-sourcing.stored_event_repository')).

If I hardcode a fallback inside the class the tests run, but this isn't a viable option obviously...
```php

namespace Spatie\EventSourcing;

final class EventSubscriber
{
    /** @var \Spatie\EventSourcing\StoredEventRepository */
    private $repository;

    public function __construct(string $storedEventRepository = '')
    {
        if ( ! $storedEventRepository ) {
            $storedEventRepository = config('event-sourcing.stored_event_repository');
        }
        $this->repository = app($storedEventRepository);
    }

    // Other methods
}
```

My test isn't related to any functionnality provided by either of the two packages.

I know this is most likely not an issue with this package in particular, nor with hyn/multi-tenant but maybe a functionality that is used by both packages and therefore creates a conflict?

Hoping you have an idea of where this could come from, because I'm shooting `dd()` in the dark right now 😅

Happy holidays!

**Comment by jdousdebes** [comment]
Hi!. Did you find a solution to your problem?

I'm having the same problem.

**Comment by fhusquinet** [comment]
Not really no... Considering making a pull request OR forking it to use it on my project instead.
Seems like a niche issue.

**Comment by freekmurze** [comment]
Closing this as I don't use multi-tenant myself. 

If there's anything simple we can do to make it compatible, send a PR.

**Comment by MannikJ** [comment]
Hi! We encounter the exact same issue without using hyn/multi-tenant. It would be very interesting what is actually happening.

**Comment by kielabokkie** [comment]
Just adding some info here for other people who happen to find this thread. For me it was a test that extended `PHPUnit\Framework\TestCase`. When changing it to extend `Tests\TestCase` instead, the test passed.

**Comment by inxilpro** [comment]
We just bumped into this, and as far as I can tell it has to do with something holding a reference to a stale copy of the event dispatcher between tests.

In our case, this looked something like:

```php
class Example
{
  protected static $cache;

  public static getCache()
  {
    if (null === static::$cache) {
      static::$cache = \Cache::tags('foo');
    }
    
    return static::$cache;
  }
}
```

When you call `Cache::tags()` that calls `setEventDispatcher()` on the `TaggedCache` instance that is created. This event dispatcher is the one bound to the DI container.

Somehow, it seems that having that reference hanging around between PHPUnit tests caused [this line](https://github.com/spatie/laravel-event-sourcing/blob/master/src/EventSourcingServiceProvider.php#L39) in the `EventSourcingServiceProvider` to try to access the wrong DI container altogether—one that doesn't have a singleton registered with it.

I'm honestly not 100% sure yet if this is something that can be solved in this package, or if it's just a gotcha related to how PHPUnit works + how Laravel hooks up events across a bunch of parts of the codebase. I'll post more if I figure out a more reliable solution.

My recommendation to anyone who is still having this problem — look around for code that stores anything statically (like above) and see if the thing you're storing statically references the event dispatcher.

In our case, the solution was:

```php
class Example
{
  protected static $cache;

  public static getCache()
  {
    if (null === static::$cache) {
      static::$cache = \Cache::tags('foo');
    }

    static::$cache->setEventDispatcher(Model::getEventDispatcher());
    
    return static::$cache;
  }
}
```

(The logic was in a model, so getting the event dispatcher from the `Model` class makes the most sense here.)
