### ISSUE TITLE
The "auto_discover_projectors_and_reactors" config works regardless of "dont-discover" in composer.json

### ISSUE THREAD

**Issue by n1crack** [spatie/laravel-event-sourcing#420]
In one of my projects, I am using laravel/telescope. It is listed in the require-dev section of my composer.json file. I am not installing the package in the production environment. Since I added it to the 'dont-discover' list, the auto-discovery feature does not load the Telescope service providers.

However, somehow the TelescopeServiceProvider still gets registered due to the following config:

```php
'auto_discover_projectors_and_reactors' => [
   app()->path(),
],
```

To fix this, I had to comment out the app()->path() line.

**Comment by sebastiandedeyne** [comment]
Not sure how this is happening because autodiscovery is kickstarted from `EventSourcingServiceProvider`, which shouldn't run when Laravel's auto-discovery is disabled.

Can you verify `EventSourcingServiceProvider`'s `register` or `boot` method are running and find out why?

Possible issues:
- Did you manually register the service provider in `config/app.php`?
- Is the service provider cached?

**Comment by n1crack** [comment]
> Did you manually register the service provider in config/app.php?


Its registered in the AppServiceProvider.php


```php
    /**
     * Register any application services.
     */
    public function register(): void
    {
        if ($this->app->environment('local')) {
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
            $this->app->register(TelescopeServiceProvider::class);
        }
    }
```


after calling 
composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
<img width="873" alt="image" src="https://github.com/spatie/laravel-event-sourcing/assets/712404/2ea88c4f-ca97-4c49-910c-1e3b6dc0f769">


after changing this line, it works.

```
'auto_discover_projectors_and_reactors' => [
   // app()->path(),
],
```

my composer.json has

```
    "extra": {
        "laravel": {
            "dont-discover": [
                "laravel/telescope"
            ]
        }
    },
```


so, In the EventSourcingServiceProvider.php

changing 
```
        (new DiscoverEventHandlers())
            ->within(config('event-sourcing.auto_discover_projectors_and_reactors'))
            ->useBasePath(config('event-sourcing.auto_discover_base_path', base_path()))
            ->ignoringFiles(Composer::getAutoloadedFiles(base_path('composer.json')))
            ->addToProjectionist($projectionist);

```
to :

```
        (new DiscoverEventHandlers())
            ->within(config('event-sourcing.auto_discover_projectors_and_reactors'))
            ->useBasePath(config('event-sourcing.auto_discover_base_path', base_path()))
            ->ignoringFiles([
                ...File::allFiles(app_path('Providers')),
                ... Composer::getAutoloadedFiles(base_path('composer.json'))
            ])
            ->addToProjectionist($projectionist);
```

I can create PR but if there is another way I would like to know.
