### ISSUE TITLE
Migration - Needs a "down()"

### ISSUE THREAD

**Issue by gcshri** [spatie/laravel-event-sourcing#44]
Not sure how to submit a PR and if it's worth it for a small issue like this.

the file create_stored_events_table.php.stub needs simple down() method to remove the created table.

```
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('stored_events');
    }
```

**Comment by freekmurze** [comment]
I generally do not add `down` functions to the migrations. I you need this, publish the migration and add it to your own project.
