### ISSUE TITLE
Installation fails if config is cached

### ISSUE THREAD

**Issue by dfoxx** [spatie/laravel-event-sourcing#47]
If you've ever run `php artisan config:cache` prior to installation you will get the following error:

```
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Spatie\EventSourcing\EventSubscriber::__construct() must be of the type string, null given, called in spatie/laravel-event-sourcing/src/EventSourcingServiceProvider.php on line 58

  at spatie/laravel-event-sourcing/src/EventSubscriber.php:9
     5| final class EventSubscriber
     6| {
     7|     private StoredEventRepository $repository;
     8| 
  >  9|     public function __construct(string $storedEventRepository)
    10|     {
    11|         $this->repository = app($storedEventRepository);
    12|     }
    13|

  Exception trace:

  1   Spatie\EventSourcing\EventSubscriber::__construct()
      spatie/laravel-event-sourcing/src/EventSourcingServiceProvider.php:58

  2   Spatie\EventSourcing\EventSourcingServiceProvider::Spatie\EventSourcing\{closure}(Object(Illuminate\Foundation\Application), [])
      laravel/framework/src/Illuminate/Container/Container.php:799

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

I now realize `config:cache` is recommended for production only:
> https://laravel.com/docs/6.x/configuration#configuration-caching
> You should typically run the php artisan config:cache command as part of your production deployment routine. The command should not be run during local development as configuration options will frequently need to be changed during the course of your application’s development.

Running `php artisan config:clear` before installing via `composer require...` will prevent this issue from occurring, but if you're already hitting this error you will need to run `rm -rf vendor && composer update && php artisan config:clear`.

I'm not sure if making a note of this is important enough to go in the installation instructions, but if you like I can submit a PR.

**Comment by freekmurze** [comment]
Thank you for your suggestion. I'm thinking that info belongs more in the Laravel docs (and I'm sure it's mentioned there somewhere) than in our docs.
