### ISSUE TITLE
installation failing

### ISSUE THREAD

**Issue by JayAhrDe** [spatie/laravel-event-sourcing#6]
On `require spatie/laravel-event-sourcing`, this is what I get.
![image](https://user-images.githubusercontent.com/930553/65497754-05426a00-debb-11e9-9a7b-1b0caf2121c1.png)

Until I delete the package, every command, e.g. `php artisan serve`, will result in an error:
![image](https://user-images.githubusercontent.com/930553/65497815-24d99280-debb-11e9-98b4-e644dbc57309.png)

Any idea?

**Comment by ahmed-alaa** [comment]
I'm not sure why package needs big memory but you can check php `memory_limit` by using
```
php -r "echo ini_get('memory_limit').PHP_EOL;"
```

Also, you can increase it inside your `php.ini` then package installation should work.

But of course maybe could be addressed/answered better by #Spati_team

**Comment by riasvdv** [comment]
With a new Laravel project and just the laravel-event-sourcing package I can go as low as 15MB of PHP memory to serve the application. Can you give us a bit more info?

- Which other composer packages have you required?
- Are you upgrading from `laravel-event-projector` or doing a new installation?

It seems weird our package would be the issue as in a new Laravel project I can install and `artisan serve` everything with as little as 15M of PHP memory

**Comment by JayAhrDe** [comment]
Thanks so far!

I tried **updating** from event-projector; when it lead to the same error, I removed it and required **event-sourcing** from scratch.

This is the composer.json (as .txt for compatibility-reasons): 

[composer.json.txt](https://github.com/spatie/laravel-event-sourcing/files/3646527/composer.json.txt)

**Comment by riasvdv** [comment]
It might be failing somehow because of the old namespaces and dumping a lot, can you try doing step 3 of the [Upgrading guide](https://github.com/spatie/laravel-event-sourcing/blob/master/UPGRADING.md) before requiring it again?

**Comment by JayAhrDe** [comment]
It's only left over in the Logs:
![image](https://user-images.githubusercontent.com/930553/65502372-f495f200-dec2-11e9-8c55-7875df08817e.png)
