### ISSUE TITLE
Question - Could it be slow to recover large amounts of events?

### ISSUE THREAD

**Issue by iBet7o** [spatie/laravel-event-sourcing#60]
I have a project focused on money transactions, I just read the excellent documentation of this repository and I think it could be of great help in my project.

But I have some doubts, the database of this type of projects generally grows very fast, I feel that aggregators when reconstructing all events (for example, 1M of transactions) would be somewhat slow.

Otherwise, if everything is super fast, would it be convenient to create a separate project to record the events and use the projectors?

I had never used event sourcing and I think it's great, I hope I don't bother with the questions.

Greetings.

**Comment by riasvdv** [comment]
v3 has Snapshots, which allows you to store the state of an aggregate at a point in time, this helps so you don’t have to reconstitute all events every time
