### ISSUE TITLE
Release of version 1.1.0 is actually version 2

### ISSUE THREAD

**Issue by m-bymike** [spatie/laravel-event-sourcing#63]
Hi,

according to the [changelog](https://github.com/spatie/laravel-event-sourcing/blob/v1/CHANGELOG.md#110---2020-02-07), 1.1.0 is supposed to contain the change `countAllStartingFrom`. But after updating with composer to 1.1.0 the package now requires PHP 7.4 (the major change of v2). It also doesn't contain the changes related to `countAllStartingFrom`.

It looks like the tag has been related to a wrong commit, it points to a merge commit on the master branch.

I'm not sure, what the best way would be to solve this. It's just that at the moment 1.1.0 doesn't contain the desired feature, and depends on PHP 7.4 ...

**Comment by m-bymike** [comment]
Just to make it easier, here with links: 
Tag [1.1.0](https://github.com/spatie/laravel-event-sourcing/releases/tag/1.1.0) points to commit f72358f0357d8bee7882b94b767cd26a1e160117

**Comment by djallits** [comment]
I am going to piggyback off this issue, because I believe it is closely related.

This is what happens when adding the library to my project, which causes a fatal error during `package:discover`.

```
$ composer require spatie/laravel-event-sourcing
Using version ^1.0 for spatie/laravel-event-sourcing
```

If I attempt to explicitly call the _v3.0_, I receive errors about not meeting library requirements.

```
$ composer require spatie/laravel-event-sourcing:^3.0
 Package spatie/laravel-event-sourcing at version ^3.0 has a PHP requirement incompatible with your PHP version (7.3) 
```

However, the version of PHP I am running passes the documented requirements:

>PHP 7.3.14 (cli) (built: Feb  1 2020 20:48:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies

**Comment by riasvdv** [comment]
This package has required PHP 7.4 from version 1.1.0, which you can see in composer.json

The requirements weren't updated in the docs correctly, I've fixed that now

**Comment by m-bymike** [comment]
@riasvdv Thank for updating the docs, but I think, this didn't address the problem.

My point is: v1.1.0 is tagging the wrong commit. As outlined above, the actual changelog for v1.1.0 is here: https://github.com/spatie/laravel-event-sourcing/blob/v1/CHANGELOG.md#110---2020-02-07. Compare this to the changelog of the tree of the tagged commit: https://github.com/spatie/laravel-event-sourcing/blob/f72358f0357d8bee7882b94b767cd26a1e160117/CHANGELOG.md

I recommend to drop the v1.1.0 tag, and create a new v1.1.1 to this commit: 851f7e61b2f7a397a149f06546c36a235d7ccdef

**Comment by freekmurze** [comment]
I'll take care of this soon!

**Comment by freekmurze** [comment]
Done!

**Comment by m-bymike** [comment]
Thank you!
