### ISSUE TITLE
CouldNotPersistAggregate with message 'not persist aggregate ActionPointAggregate (uuid: ) because it seems to be changed by another process after it was retrieved in the current process. Expect to persist events after version 0, but version 1 was already persisted.'

### ISSUE THREAD

**Issue by ccgintranet** [spatie/laravel-event-sourcing#65]
Hello,

I am wondering if there is a way to incorporate Spatie Event Sourcing with Behat (Gherkin)?

I am holding onto AggregateRoot references throughout the entire lifecycle of each scenario in order to test the "behaviour" of my business logic.

What I am finding is, due to the way AggregateRoot::fake() is implemented, there can be a clash when attempting to use the testing in the manner in which it was originally designed; assuming targeted for PHPUnit where tearDown() will rollback any data so there would never be a "blank" uuid which would clause version classes among different aggregate roots or events.

The tests can obviously be made to work by actually using the AggregateRoots normally (by providing a UUID and persisting to SQLIte) - but I am wondering if there's another way around this so we can use the testing in the way it was supposed to be used.

Thanks,

Kind Regards,
Michael

**Comment by freekmurze** [comment]
I'd welcome a PR that fixes this. If none comes in I'll take a look when I have the time.

**Comment by freekmurze** [comment]
I'm not a user of Behat myself, so I am not going to invest time in this issue. 

I'd welcome a PR that fixes this.
