### ISSUE TITLE
Syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

### ISSUE THREAD

**Issue by emaikongebm** [spatie/laravel-event-sourcing#69]
I'm trying to install spatie/laravel-event-sourcing. It has no problem until it reached this point : 

`@php artisan package:discover --ansi`

When it reached this problem, an error showed up, and it said : 

`In EventSourcingServiceProvider.php line 64:`

  `syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'`

`Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

`Installation failed, reverting ./composer.json to its original content.`

I located the file but I'm afraid to change the vendor files, worrying it might ruin the library.

**Comment by riasvdv** [comment]
Are you on PHP 7.4?

**Comment by emaikongebm** [comment]
> Are you on PHP 7.4?

I'm on PHP 7.3.8

**Comment by riasvdv** [comment]
This package only works on PHP 7.4

**Comment by Dgalhotra** [comment]
I'm using php 7.4 still getting this error
