### ISSUE TITLE
Option to get all events for one account

### ISSUE THREAD

**Issue by goranculibrk** [spatie/laravel-event-sourcing#7]
Hi there, this is more a question than it is an issue. 
I'm trying to figure out how I can get a list of all events for specific account.
An example from Larabank. I would like to create a list of transaction for specific account, when user deposited or withdraw the money from the account to give a user option to see the activity on their account. 
By using event replay I can see that it's possible, but I'm not sure how to get to that data.
Thanks.

**Comment by lizhineng** [comment]
I create a dedicated `AccountTransactionProjector` for account transaction list.

**Comment by goranculibrk** [comment]
@lizhineng Thanks for pointing me to the right direction. I've missed that in `stored_events` the `aggregate_uuid` is the actually the uuid of the account in the `accounts` table.
