### ISSUE TITLE
Returning back the data after we create/update it

### ISSUE THREAD

**Issue by emaikongebm** [spatie/laravel-event-sourcing#70]
I'm using spatie/laravel-event-sourcing library.

I'll explain my issue using food and beverage system logic.
Say that I have 2 classes, which is SalesOrder and Table. When SalesOrder is created using the event-sourcing library, I need to return back the created SalesOrder data because I need to assign the SalesOrder's id to the Table's sales_order_id property so that I can link to both SalesOrder->Table and SalesOrder<-Table, and by system I can get the SalesOrder's data only by Table's id.

Is there any ways to return the created/updated data back to my coding section where I need to assign the SalesOrder's id to Table's sales_order_id?

**Comment by riasvdv** [comment]
You can create a `uuid` and pass that along with your event, after the event has been stored and applied you can retrieve your model through the `uuid`

**Comment by emaikongebm** [comment]
@riasvdv I got this error when returning the created data : 

`Call to undefined method `App\Models\SalesOrder::uuid()` `

My method's code are:
public static function createSalesOrder(array $attributes)
    {
        $attributes['uuid'] = (string) Uuid::uuid4();
        event(new SalesOrderCreatedEvent($attributes));
        return static::uuid($attributes['uuid']);
    }

My event : 
class SalesOrderCreatedEvent implements ShouldBeStored
{
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public $salesOrderAttributes;

    public function __construct(array $salesOrderAttributes)
    {
        $this->salesOrderAttributes = $salesOrderAttributes;
    }
}

My Projector : 
class SalesOrderProjector implements Projector
{
    use ProjectsEvents;

    public function onSalesOrderCreated(SalesOrderCreatedEvent $event)
    {
        $date = date("Y-m-d H:i:s", strtotime($event->salesOrderAttributes["ordered_at"]));
        $event->salesOrderAttributes["ordered_at"] = $date;
        SalesOrder::create($event->salesOrderAttributes);
    }
}
