### ISSUE TITLE
composer require laravel-event-sourcing problem

### ISSUE THREAD

**Issue by sehs1418** [spatie/laravel-event-sourcing#71]
when i try to install the package with composer in my laravel project i get this problem

Illuminate\Foundation\ComposerScripts::postAutoloadDump

> @php artisan package:discover --ansi
PHP TypeError:  Argument 1 passed to Spatie\EventSourcing\EventSubscriber::__construct() must be of the type string, null given, called in /var/www/html/livebox-laravel/vendor/spatie/laravel-event-sourcing/src/EventSourcingServiceProvider.php on line 59 in /var/www/html/livebox-laravel/vendor/spatie/laravel-event-sourcing/src/EventSubscriber.php on line 10

**Comment by aibarra11** [comment]
i ran into this problem as well. brand new project laravel 7 with php7.4 (in docker alpine with fpm)

if you're ok to, delete your composer.lock file. The entry for this won't be in composer.json but in composer.lock

```
php artisan composer update

php artisan config:clear

php artisan cache:clear
```

this worked for me in my new project

**Comment by denjaland** [comment]
Hmm.  Not sure why, but even after deleting /vendor, clearing whatever cache we had, even rebooting the computer and then trying to install it, we keep on running into the exact same issue.

I guess this could be resolved by adding a default value for the config retrieved here: https://github.com/spatie/laravel-event-sourcing/blob/master/src/EventSourcingServiceProvider.php#L64, passing in `\Spatie\EventSourcing\EloquentStoredEventRepository::class`as the default value?

**Comment by ifaniqbal** [comment]
Try to delete files in `bootstrap/cache` (except .gitignore). Worked in my case.

**Comment by Azeirah** [comment]
For others who're having this problem, it's related to the fourth step of the upgrading guide

> All classes that revolve around the concept of stored events have been moved to the Spatie\EventSourcing\StoredEvents namespace. If you are using any of those classes, take a look inside the source code of the package what the new namespace is.

See my changes in `config/event-sourcing.php`

```
diff --git a/server/config/event-sourcing.php b/server/config/event-sourcing.php
index 068d290..74afcc0 100644
--- a/server/config/event-sourcing.php
+++ b/server/config/event-sourcing.php
@@ -46,14 +46,14 @@ return [
      * To add extra behaviour you can change this to a class of your own. It should
      * extend the \Spatie\EventSourcing\Models\EloquentStoredEvent model.
      */
-    'stored_event_model' => \Spatie\EventSourcing\Models\EloquentStoredEvent::class,
+    'stored_event_model' => \Spatie\EventSourcing\StoredEvents\Models\EloquentStoredEvent::class,

     /*
      * This class is responsible for handle stored Events. To add extra behaviour you
      * can change this to a class of your own. The only restriction is that
      * it should implement \Spatie\EventSourcing\StoredEventRepository.
      */
-    'stored_event_repository' => \Spatie\EventSourcing\EloquentStoredEventRepository::class,
+    'stored_event_repository' => \Spatie\EventSourcing\StoredEvents\Repositories\EloquentStoredEventRepository::class,

     /*
      * This class is responsible for handling stored events. To add extra behaviour you
```
