### ISSUE TITLE
Bring PHP version requirement in line with Laravel

### ISSUE THREAD

**Issue by renedekat** [spatie/laravel-event-sourcing#74]
Hello,

What's the reason that your packages require PHP7.4 and do not follow the same requirements as the Laravel framework.

When working in a business environment with large server farms, it's not always possible to keep up to date with the latest PHP versions. 

I don't see any reason why older PHP version can't be supported. as there's nothing in PHP7.4 that important to warrant not supporting 7.2 or 7.3

**Comment by freekmurze** [comment]
> I don't see any reason why older PHP version can't be supported.

All projects we use this package on are on PHP 7.4. It makes no sense for us to invest time in supporting older versions. PHP 7.4 allows us to write better code.

Feel free to invest your own time in creating and maintaining support for older PHP versions.

**Comment by renedekat** [comment]
Hi @freekmurze, I completely understand and I'd do the same in your situation. Still pushing to get an upgrade to PHP7.4 here :)

That being said, Spatie open source projects are widely used and highly regarded. Which means they're very likely to be used by companies that don't/can't upgrade as fast as you can, and I think that comes with a certain responsibility.

But in short, great work on this and all of your other projects. Been a fan and happy user for years.

Cheers,
René
