### ISSUE TITLE
Aggregate not replaying events since V3 upgrade.

### ISSUE THREAD

**Issue by nrobates** [spatie/laravel-event-sourcing#76]
Hello,

The issue seems to be that since I have upgraded to version 3 and followed the steps in the upgrade guide, the events based on an aggregate are now no longer being replayed. 

I am assuming that this is because the `aggregate_version` column in the database has a `NULL` value for every stored event. Is there a way already available to fix this, or is there a suggested way that this could be done.

I appreciate any feedback.

Thanks.

**Comment by freekmurze** [comment]
I'm not rely sure why it isn't replaying in your project, but it won't hurt filling in those aggregate_version fields with an incremental value.

**Comment by nrobates** [comment]
Hello again. I managed to track it down to the retrieveAllAfterVersion method in the EloquentStoredEventRepository.php file. 

I am not sure that I was completely clear in my original message. This happens, not when replaying events from the command line, but when you retrieve an aggregate and it replays the events to bring your aggregate to the current state. The method called is expecting a version, which gets passed in as 0, so no stored events are returned from that call as all of the stored events have the aggregate_version value as NULL.

Is it safe to set all of the aggregate_version values as 0 or would there be a good way to run the command replay and it could then assign version numbers to the events as it replays?

Thanks again.

**Comment by freekmurze** [comment]
I'm thinking the safest way would be to set the aggregate version to an incrementing value. Maybe just setting it to the same value as `id` would do the trick.

**Comment by nrobates** [comment]
Sounds good. Thanks Freek!
