### ISSUE TITLE
Question - Implementing rollback/undo functionality

### ISSUE THREAD

**Issue by aureliusm** [spatie/laravel-event-sourcing#77]
Hi,

thanks for another awesome package. I have a question which I can't wrap my head around. 

I would like to enable end-user to be able to go back to any point in time by giving him an option to go back to some specific point in the `stored_events` table and "reset" state to that point. 

How would you approach this problem? I am thinking of replaying certain aggregate root to a specific point and find out the actual state at that point and then adding another event to reset state. Does that sound fine?

Thanks for your answers!

**Comment by jitendra-1217** [comment]
Sounds good to me what you suggested.
Just checking how did you do it finally?

**Comment by aureliusm** [comment]
@jitendra-1217 Thanks for responding. Didn't get to it yet. :) Will post here when I am done.

**Comment by riasvdv** [comment]
> I am thinking of replaying certain aggregate root to a specific point and find out the actual state at that point and then adding another event to reset state. Does that sound fine?

That does sound fine, closing this, we'll move it to discussions when it gets activated by Github on this repository
