### ISSUE TITLE
Missing created_at from snapshots

### ISSUE THREAD

**Issue by minicstudio** [spatie/laravel-event-sourcing#78]
Seems just found a bug with snapshots during my testing. The created_at attribute is missing and the SQL raises an error.

Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1364 Field 'created_at' doesn't have a default value (SQL: insert into `snapshots` (`aggregate_uuid`, `aggregate_version`, `state`) values (x, x, x)) in file ...

**Comment by freekmurze** [comment]
Strange... the table is created by our default migration: https://github.com/spatie/laravel-event-sourcing/blob/master/stubs/create_snapshots_table.php.stub#L16

**Comment by antal-levente** [comment]
Yes i know that. That was the first thing i checked, because wasn't sure if we added the created_at column or was there by default.

Are you going to remove the column from the migration or fix the issue differently?

**Comment by antal-levente** [comment]
I don't understand why you closed when it's clearly a bug. Without a fix snapshots creation is not working ... or am i missing something? Nothing states that i should provide the created_at timestamp somehow.

**Comment by freekmurze** [comment]
I didn't understand the problem correctly. Meanwhile I've made a new released where the `created_at` field will be filled automatically.

**Comment by antal-levente** [comment]
Yes, that was the problem. Maybe i wasn't clear enough, sorry for that and thanks for the quick fix.
