### ISSUE TITLE
Scheduling commands or events

### ISSUE THREAD

**Issue by gustavopch** [spatie/laravel-event-sourcing#79]
Hey, some ES/CQRS implementations provide scheduling capabilities out-of-the-box.

Use case example:
- an order is placed
- the order is delivered to the buyer (at this moment, we schedule a job to ask the buyer for feedback in 1 hour)
- user is asked for feedback

Reference from Elixir's Commanded: https://hexdocs.pm/commanded_scheduler/Commanded.Scheduler.html

Are there any plans to incorporate such feature into this library? Or could you provide any guidance on how you'd accomplish the same result by integrating this library with some scheduler tool?

Edit: I'm not familiar with PHP or the Laravel ecosystem.

**Comment by freekmurze** [comment]
Laravel itself has a scheduler that allows you to schedule anything you'd like: https://laravel.com/docs/master/scheduling#introduction

**Comment by gustavopch** [comment]
@freekmurze Thank you for pointing me in the right direction.
