### ISSUE TITLE
The replay command should have a --force flag

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-event-sourcing#84]
To be consistent with other Laravel commands, running `php artisan event-sourcing:replay --force` should run without a confirmation prompt.

**Comment by pascualstromsnes** [comment]
Hello @sebastiandedeyne 

I have made a PR (#86) that includes an implementation of a force flag and a corresponding test.

**Comment by freekmurze** [comment]
Thanks @pascualstromsnes, we'll continue this in #86
