### ISSUE TITLE
store unicode into marianDB

### ISSUE THREAD

**Issue by anhducbkhn** [spatie/laravel-event-sourcing#87]
This is my env:
- DB: MarianDB: 10.3.14
- PHP: 7.4
- composer:
-- "require": {
        "php": "^7.2.5",
        "cerbero/laravel-enum": "^1.2",
        "fideloper/proxy": "^4.3.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "7.5.2",
        "laravel/helpers": "^1.2.0",
        "laravel/passport": "^8.4.3",
        "laravel/tinker": "^2.4.0",
        "laravel/ui": "^2.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "maatwebsite/excel": "^3.1",
        "sentry/sentry-laravel": "1.7.0",
        "spatie/laravel-event-sourcing": "^3.1",
        "spatie/laravel-permission": "^3.6",
        "writingink/wink": "^0.2"
    },

When I store event into stored_events table, data at event_properties column will like this:
   ` {"data":{"_token":"xy6f18aLmexqgW9ugRm3EWDcY9ZaX5mAhiFRmbOs","name":"\u0110\u1ee9c - Customer 3","email":"anhduc.bkhn+3@gmail.com","password":"123456","password_confirmation":"123456","uuid":"fcf7fa80-27f5-413a-b5cf-ce20c5571702"}}`

I tried with mysq 5.7, coumn will like this:
  `  {"data": {"name": "Đức customer 5", "uuid": "e86d939b-8141-4d36-9429-17c5b566be0f", "email": "anhduc.bkhn+5@gmail.com", ...`

The different is "name" attribute.  mysql store "name": "Đức customer 5", but mariaDB store "name":"\u0110\u1ee9c - Customer 3".

I tested with sql command on mariaDB:
```
insert into stored_events (event_class, event_properties, meta_data)
values ('sg', '{"test":"Đức"}', 'sg')
```

It still work well!

How to store data like mysql 5.7?

**Comment by freekmurze** [comment]
Seems to me that this is not an issue with the package itself. I possible just use MySQL 5.7.

**Comment by anhducbkhn** [comment]
I customized class JsonEventSerializer:

`
use Symfony\Component\Serializer\Encoder\JsonEncode;
public function __construct()
    {
        $encoders = [new JsonEncoder(new JsonEncode(['json_encode_options' =>  JSON_UNESCAPED_UNICODE]))];
        $normalizers = [new DateTimeNormalizer(), new ObjectNormalizer()];

        $this->serializer = new SymfonySerializer($normalizers, $encoders);
    }
`

it worked.

**Comment by freekmurze** [comment]
Nice, glad you were able to find a solution.
