### ISSUE TITLE
[Proposal] Allow disabling reactors temporarily

### ISSUE THREAD

**Issue by tonysm** [spatie/laravel-event-sourcing#88]
Hi, all.

I'm implementing event sourcing on an existing app using the package and after moving the side-effects to reactors, I had a couple of tests failing. The project isn't using aggregators, but only events and eloquent models for now, and I have an observer that intercepts model changes and dispatches the correct events.

Tests were previously using model factories and I got myself wanting to disable reactors (temporarily). Something like this:

```php
$model = Projectionist::withoutReactors(function () {
  // No reactors will be triggered
  return factory(MyModel::class)->create();
});
```

Some other possible syntax:

```php
Projectionist::withoutReactors(); // clears up all reactors
Projectionist::withoutReactors([MySideEffect::class]); // disables only this specific reactor
```

Is this something we can have on the package? If so, I could send a PR.

The existing `Projectionist::withoutEventHandlers()` doesn't quite work for this case because I want the projectors to run, but not the reactors.

**Comment by freekmurze** [comment]
Hi Tony,

I like this syntax, because it leans to the already existing `Projectionist::withoutEventHandlers()`

```
Projectionist::withoutReactors(); // clears up all reactors
Projectionist::withoutReactors([MySideEffect::class]); // disables only this specifi
```

Feel free to PR that! Thanks 👍

**Comment by tonysm** [comment]
Figured I could simply add a test helper method, like this:

```php
public function withoutReactors($scope)
{
  $reactors = Projectionist::getReactors();

  try {
    return call_user_func($scope);
  } finally {
    Projectionist::addReactors($reactors->all());
  }
}
```
