### ISSUE TITLE
Can't unserialize event which contains Carbon property type

### ISSUE THREAD

**Issue by huuhoa0506** [spatie/laravel-event-sourcing#98]
I try to create an event with Illuminate\Support\Carbon property , i get an exception 
 "message": "Failed to unserialize an event with class `App\\Aggregates\\Reward\\Events\\PointGave` on stored event with id `6`. Are you sure that event class exists? ", "exception": "Spatie\\EventSourcing\\Exceptions\\InvalidStoredEvent", ...

How to resolve this issue without a custom event serializer implementaion  ??
Thanks for your answers!

**Comment by freekmurze** [comment]
I'm thinking you could let your event hold the timestamp value and not a carbon instance.

**Comment by huuhoa0506** [comment]
> I'm thinking you could let your event hold the timestamp value and not a carbon instance.

Thank you!
